# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# Not for Jekyll v3
# relative_permalinks: true

# Setup
title:               Hafsteinn
tagline:             'PhD candidate in CS @ ETHZ'
description:         'A blog by <a href="https://twitter.com/hafsteinn" target="_blank">@hafsteinn</a>.'
url:                 http://haffi112.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hafsteinn Einarsson
  url:               https://twitter.com/hafsteinn
  email:             haffie@gmail.com

# Custom vars
version:             0.0.1

social:
- user:              hafsteinn
  url:               https://twitter.com/hafsteinn
  logo:              /assets/twitter-logo.svg
- user:              Hafsteinn
  url:               https://www.linkedin.com/in/hafsteinn-einarsson-619a3711
  logo:              /assets/linkedin-logo.svg
- user:              Hafsteinn
  url:               https://www.goodreads.com/user/show/3584182-haffi
  logo:              /assets/goodreads-logo.svg
- user:              Haffi112
  url:               https://github.com/Haffi112
  logo:              /assets/github-logo.svg

# Gems
gems:                [jekyll-paginate]
