// Generate cv/data.typ from site sources, then compile both CVs to public/.
//
// Sources of truth:
//   - src/data/cv-static.yaml           (positions, education, awards, service)
//   - src/data/publications.json        (publications — generated by parse-bib)
//   - src/content/students/*.yml        (PhDs, committee, MSc, alumni)
//   - src/content/teaching/*.yml        (courses)
//   - src/content/projects/*.yml        (open-source projects)
//   - src/content/talks/*.yml           (talks and outreach)
//
// Outputs:
//   - cv/data.typ                       (Typst dictionary)
//   - public/cv.pdf                     (short, 2-3 pages)
//   - public/cv-long.pdf                (full, all publications)

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

const STATIC_CV = path.join(ROOT, 'src/data/cv-static.yaml');
const PUBLICATIONS = path.join(ROOT, 'src/data/publications.json');
const STUDENTS_DIR = path.join(ROOT, 'src/content/students');
const TEACHING_DIR = path.join(ROOT, 'src/content/teaching');
const PROJECTS_DIR = path.join(ROOT, 'src/content/projects');
const TALKS_DIR = path.join(ROOT, 'src/content/talks');

const CV_DIR = path.join(ROOT, 'cv');
const DATA_TYP = path.join(CV_DIR, 'data.typ');
const SHORT_PDF = path.join(ROOT, 'public/cv.pdf');
const LONG_PDF = path.join(ROOT, 'public/cv-long.pdf');

// ---------- Typst value serialization ----------

function escapeTypstString(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

function toTypst(value: unknown, indent = 0): string {
  const pad = '  '.repeat(indent);
  const next = '  '.repeat(indent + 1);

  if (value === null || value === undefined) return 'none';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return `"${escapeTypstString(value)}"`;
  if (value instanceof Date) {
    return `"${value.toISOString().slice(0, 10)}"`;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return '()';
    const items = value.map((v) => `${next}${toTypst(v, indent + 1)},`).join('\n');
    return `(\n${items}\n${pad})`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return '(:)';
    const items = entries
      .map(([k, v]) => `${next}${typstKey(k)}: ${toTypst(v, indent + 1)},`)
      .join('\n');
    return `(\n${items}\n${pad})`;
  }
  return `"${escapeTypstString(String(value))}"`;
}

function typstKey(key: string): string {
  if (/^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(key)) return key;
  return `"${escapeTypstString(key)}"`;
}

// ---------- Data loaders ----------

function loadYamlDir(dir: string): Array<Record<string, unknown>> {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))
    .map((f) => yaml.load(readFileSync(path.join(dir, f), 'utf8')) as Record<string, unknown>);
}

interface Publication {
  id: string;
  title: string;
  authors: Array<{ first: string; last: string }>;
  venue: string;
  year: number;
  theme?: string;
  summary?: string;
  selected: boolean;
  links: Record<string, string>;
  notes?: string;
}

interface Student {
  name: string;
  role: 'phd-main' | 'phd-committee' | 'msc' | 'alumni-phd' | 'alumni-msc' | 'alumni-phd-committee';
  title?: string;
  startYear?: number;
  endYear?: number;
  link?: string;
  nowAt?: string;
}

interface Course {
  title: string;
  level: 'bsc' | 'msc' | 'phd' | 'mixed';
  language: 'english' | 'icelandic' | 'mixed';
  description: string;
  semesters: string[];
}

interface Project {
  name: string;
  summary: string;
  links?: Record<string, string>;
  tags?: string[];
  status: 'active' | 'maintenance' | 'archived';
}

interface Talk {
  date: Date | string;
  title: string;
  venue: string;
  location?: string;
  link?: string;
  type: 'invited' | 'keynote' | 'outreach' | 'workshop';
}

const THEME_LABELS: Record<string, string> = {
  'nlp-is': 'NLP for Icelandic and Germanic languages',
  'cv-nat': 'Computer vision for natural sciences',
  'clinical-ai': 'Clinical AI and cardiology',
  genetics: 'Human genetics and computational biology',
  'comp-neuro': 'Computational neuroscience'
};
const THEME_ORDER = ['nlp-is', 'cv-nat', 'clinical-ai', 'genetics', 'comp-neuro'];

// ---------- Main ----------

function main() {
  const staticData = yaml.load(readFileSync(STATIC_CV, 'utf8')) as Record<string, unknown>;
  const publications = JSON.parse(readFileSync(PUBLICATIONS, 'utf8')) as Publication[];
  const students = loadYamlDir(STUDENTS_DIR) as unknown as Student[];
  const courses = loadYamlDir(TEACHING_DIR) as unknown as Course[];
  const projects = loadYamlDir(PROJECTS_DIR) as unknown as Project[];
  const talks = loadYamlDir(TALKS_DIR) as unknown as Talk[];

  // Group students by role
  const phd_main = students.filter((s) => s.role === 'phd-main');
  const phd_committee = students.filter((s) => s.role === 'phd-committee');
  const phd_committee_alumni = students
    .filter((s) => s.role === 'alumni-phd-committee')
    .sort((a, b) => (b.endYear ?? 0) - (a.endYear ?? 0));
  const msc_current = students.filter((s) => s.role === 'msc');
  const alumni_msc = students
    .filter((s) => s.role === 'alumni-msc')
    .sort((a, b) => (b.endYear ?? 0) - (a.endYear ?? 0));

  // Sort courses: MSc/PhD first
  const levelOrder: Record<string, number> = { phd: 0, msc: 1, mixed: 2, bsc: 3 };
  courses.sort((a, b) => (levelOrder[a.level] ?? 9) - (levelOrder[b.level] ?? 9));

  // Sort talks by full date desc so entries within a year are chronological
  const talksWithYear = talks
    .map((t) => ({ ...t, year: new Date(t.date).getUTCFullYear() }))
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  // Selected publications + by-theme
  const selected_pubs = publications
    .filter((p) => p.selected)
    .sort((a, b) => b.year - a.year);

  const byTheme: Record<string, Publication[]> = {};
  for (const theme of THEME_ORDER) byTheme[theme] = [];
  for (const p of publications) {
    if (p.theme && byTheme[p.theme]) byTheme[p.theme].push(p);
  }
  const publications_by_theme = THEME_ORDER.filter((t) => byTheme[t].length > 0).map(
    (t) => ({
      theme: t,
      label: THEME_LABELS[t],
      entries: byTheme[t]
    })
  );

  // Assemble the data dictionary
  const data = {
    contact: staticData.contact,
    research_statement: (staticData.research_statement as string).trim(),
    current_positions: staticData.current_positions,
    previous_positions: staticData.previous_positions,
    education: staticData.education,
    awards: staticData.awards_and_grants,
    service: staticData.service,
    outreach: staticData.outreach,
    media_appearances: staticData.media_appearances ?? [],
    collaborations: staticData.collaborations,

    phd_main,
    phd_committee,
    phd_committee_alumni,
    phd_committee_alumni_count: phd_committee_alumni.length,
    msc_current,
    msc_current_count: msc_current.length,
    alumni_msc,
    alumni_msc_count: alumni_msc.length,

    teaching: courses,
    projects,
    talks: talksWithYear,

    selected_pubs,
    publications_by_theme,
    total_publications: publications.length
  };

  const header = `// Auto-generated by scripts/generate-cv.ts — do not edit by hand.
// Sources: src/data/cv-static.yaml, src/data/publications.json, and the
// students/teaching/projects/talks content collections.
//
// To regenerate: npm run cv
`;

  const body = `#let data = ${toTypst(data)}\n`;
  writeFileSync(DATA_TYP, header + '\n' + body);
  console.log(`Wrote ${DATA_TYP}`);

  // Compile both CVs
  compile(path.join(CV_DIR, 'short.typ'), SHORT_PDF);
  compile(path.join(CV_DIR, 'long.typ'), LONG_PDF);
}

function compile(src: string, out: string) {
  console.log(`Compiling ${path.relative(ROOT, src)} → ${path.relative(ROOT, out)}`);
  execFileSync(
    'typst',
    ['compile', '--root', ROOT, '--font-path', path.join(CV_DIR, 'fonts'), src, out],
    { stdio: 'inherit' }
  );
}

main();
